### ISSUE TITLE
Account management

### ISSUE THREAD

**Issue by WTWtesting** [HTTP3D/WalkTheWeb#5]
**Logging in:**

When you add email and password and click login, there should be a wheel or something so the user understand the logging in process started and its not just that the system is not responding.

![image](https://user-images.githubusercontent.com/123270827/213886736-9f48b005-4140-4ebf-91ee-e9d107aa9b29.png)

The page (image above) does not change until you refresh from the browser (combined with the point above, user may wait for some time and leave the platform thinking logging in doesn't work). That’s when you can see you are actually logged in:

![image](https://user-images.githubusercontent.com/123270827/213886760-9b11dd12-c282-4a9c-8029-3ff24f7920c4.png)

**Creating an account :**

I added the details in create account form and clicked twice. I ended up with a duplicated account:

![image](https://user-images.githubusercontent.com/123270827/213886714-edfb0914-39d6-44be-ab05-86294ee6f0e9.png)

**Comment by adishno** [comment]
You are correct we need a progress bar and to disable the button from a second click while it processes. A second progress bar is needed to determine the avatar is loading (especially some of the larger file avatars). I'll add it to my todo list. I am currently working on a new set of 3D In-game login screens and menus so that it works better with VR and AR opposed to the current HTML overlay screens. It should be out very soon! Thanks for the feedback.

**Comment by adishno** [comment]
The "Loading Avatar" 3D Object has been added.
