### ISSUE TITLE
Web Alias deletion

### ISSUE THREAD

**Issue by WTWtesting** [HTTP3D/WalkTheWeb#7]
Created a web Alias. then deleted it. But it is still in the wtw_webalieases table.

**Comment by adishno** [comment]
Many of the deletes are merely records in the table flagged as deleted. This helps to track changes and what admin user did them.  It also makes it easy to undo deletes (if needed).  

I will double check to make sure the deleted record did not show up on the website view. (I am guessing this may be the case). 

Otherwise, maybe I should add a cleanup process in admin to remove records flagged as deleted.

Great feedback, Thanks!

**Comment by adishno** [comment]
I added a clean-up process to my list of coding to-do. Thanks!
